# app.yaml
runtime: nodejs18  # Elige una versi칩n LTS de Node.js soportada (ej: nodejs16, nodejs18, nodejs20)
instance_class: F1 # Clase de instancia b치sica, buena para empezar y para la capa gratuita

# Configuraci칩n para que App Engine use tu script "start" de package.json
# y deje que tu servidor Node.js/Express maneje el enrutamiento y los archivos est치ticos.
handlers:
- url: /.* # Enviar todas las solicitudes a tu script
  script: auto